<?php
// ========================================================================
// FrostByte
// by Roland Strålberg
// All Rights Reserved 
// Contact: rstralberg@pm.me
// ========================================================================
//
// Scan Fonts 
// - Scans for avaible fonts and returns their names in an array
// - Also generates a fonts.css file declaring them
// - 

function generate_fonts()
{
    $css = '/* Autogenerated by FrostByte */' . PHP_EOL;
    $fonts = array();
    $fontfiles = glob('../public/fonts/*.ttf');
    foreach ($fontfiles as $font) {
        $parts = pathinfo($font);
        $ff = '@font-face {' . PHP_EOL 
            . '    font-family:' . $parts['filename'] . ';' . PHP_EOL
            . '    src: url(../fonts/' . $parts['basename'] . ');'. PHP_EOL
            . '}' . PHP_EOL;
        $css .= $ff;
        array_push( $fonts, $parts['filename'] );
    }
    
    $cssfile = glob( '../public/css/fonts.css');
    $fh = fopen($cssfile[0], 'w');
    fwrite($fh, $css);
    fclose($fh);

    return $fonts;
}
?>